### ISSUE TITLE
Python 3.10 wheels

### ISSUE THREAD

**Issue by AntoineD** [pdfo/pdfo#15]
Hello,

would it be possible to get the wheels for python 3.10?

Cheers.

**Comment by ragonneau** [comment]
Hi @AntoineD,

Sorry for the delay. I uploaded the wheels for Python 3.10 (only for the latest version, i.e., [v1.2](https://pypi.org/project/pdfo/1.2/)).

Thanks for reminding me,
Cheers,
Tom.

**Comment by AntoineD** [comment]
Awesome! Thanks a lot.
