### ISSUE TITLE
Wheel file download?

### ISSUE THREAD

**Issue by dsanalytics** [pdfo/pdfo#2]
Dear Tom & Zhang, 

Thank you for making this lib available in python - appreciated.

However, would you mind preparing a whl file for this library and making it available for download here? I cannot install pdfo with pip on Windows for some reason and I'm getting many errors. I'm also hoping that fortran compiler is not needed at all if whl file is used - correct? I gather that this python lib is actually just a wrapper around the original fortran lib - which is fine for as long as I don't have to install Visual Studio, fortran compiler, and many other things I'd not usually need with most 3rd party python libs that I install and use. I'm hoping that pdfo whl file will have everything including compiled fortran lib. I'm using VS Code and Python 3.

Thanks in advance.

**Comment by jgiret** [comment]
Hello @dsanalytics , and thanks @zaikunzhang and @ragonneau for this nice library!

It's not a wheel, but you can find pre-built pdfo packages for several targets using conda and the channel conda-forge: https://anaconda.org/conda-forge/pdfo

It may suit your needs.

Best,
JC

**Comment by pdfo** [comment]
Hello @jgiret , thank you very much for staging PDFO on conda. This is great!

Hello @dsanalytics , sorry for the late response. Thanks to the pre-built PDFO packages on conda by @jgiret , we hope your problem is solved. 

Thank you.

Tom and Zaikun
