### ISSUE TITLE
ImportError: gethuge is missing.

### ISSUE THREAD

**Issue by Katherine-Gilber** [pdfo/pdfo#27]
environment: python3.8.5
use pip install pdfo
run rosenbrock_example.py
The compiler reported an importerror: File "...\lib\site-packages\pdfo\_dependencies.py", line 582, in prepdfo
    import_error_so('gethuge') 
File "...\site-packages\pdfo\_dependencies.py", line 3628, in import_error_so
    raise ImportError('{} is missing. Please reinstall {} and ensure the '
ImportError: gethuge is missing. Please reinstall pdfo and ensure the fulfilment of the requirements (numpy>=1.20.0).

**Comment by ragonneau** [comment]
Hi @Katherine-Gilber, sorry for the delay.

May I know which operating system you are using?

Also, could you please run
```bash
pip uninstall pdfo
pip install pdfo --no-cache-dir
```
and provide the outputs?

Thank you very much!

**Comment by MJDRobbins** [comment]
Hello.  Thank you for looking into this issue.

I have the same issue as Katherine-Gilber. I am an Anaconda user (conda 4.14.0 with Python 3.9.12) on Windows64 and downloaded the pdfo 1.2 package via the conda installer (https://anaconda.org/conda-forge/pdfo).

When trying to run the rosenbrock_example code I get the following message (note that I have numpy 1.21.5 installed).  Thanks for any help!

********

1. Nonlinear constraints --- ||x||_2^2 = 1, x(i)^2 >= x(i+1) >= 0.5*x(i) >= 0 for i = 1, 2:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

Traceback (most recent call last):

  File "C:\Users\....\anaconda3\lib\site-packages\pdfo\_dependencies.py", line 580, in prepdfo
    from .gethuge import gethuge

ImportError: numpy.core.multiarray failed to import


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\....\Documents\Python\DFO\Powell DFO\rosenbrock_example_pdfo.py", line 58, in <module>
    res = pdfo(chrosen, x0, bounds=bounds, constraints=[lin_con, nonlin_con_ineq, nonlin_con_eq])

  File "C:\Users\....\anaconda3\lib\site-packages\pdfo\_pdfo.py", line 182, in pdfo
    prepdfo(fun, x0, args, method, bounds, constraints, options)

  File "C:\Users\....\anaconda3\lib\site-packages\pdfo\_dependencies.py", line 582, in prepdfo
    import_error_so('gethuge')

  File "C:\Users\....\anaconda3\lib\site-packages\pdfo\_dependencies.py", line 3628, in import_error_so
    raise ImportError('{} is missing. Please reinstall {} and ensure the '

ImportError: gethuge is missing. Please reinstall pdfo and ensure the fulfilment of the requirements (numpy>=1.20.0).

**Comment by ragonneau** [comment]
Hi @MJDRobbins,

The conda-forge stating of PDFO is not maintained by us. Could you please try installing PDFO using ``pip`` (also available in Anaconda)?

Thank you,
Tom.

**Comment by MJDRobbins** [comment]
Hello @ragonneau ,

I followed your advice, first removing the conda-forge installation then using "python -m pip install pdfo" installation.  The package works for me so far.  Thank you for your prompt assistance!

Best regards,
Matt

**Comment by RobertoDiGiuseppe** [comment]
Hello @ragonneau,

I tried to install pdfo by using pip install, but I've always the same problem. Numpy is 1.23.4, virtual environment with python 3.8.13.

![Capture](https://user-images.githubusercontent.com/120196567/221195794-1567602a-e6cb-4441-9f3c-6e0c727e85d3.PNG)

Kind regards,
Rob

**Comment by ragonneau** [comment]
This error should be patched by the most recent version of PDFO on PyPI (v1.3). Please reopen this issue if it occurs again in the future.

Cheers,
Tom.

**Comment by brockho** [comment]
Hi. Unfortunately, I have the same problem as well:
```
Traceback (most recent call last):
  File "C:\Users\dimo\AppData\Roaming\Python\Python312\site-packages\pdfo\_common.py", line 405, in prepdfo
    from .gethuge import gethuge
ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimo\Desktop\coco\coco-experiment\build\python\example\example_experiment2.py", line 175, in <module>
    output  = pdfo.pdfo(problem, -5 + 10 * np.random.rand(problem.dimension), method='newuoa')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimo\AppData\Roaming\Python\Python312\site-packages\pdfo\_pdfo.py", line 265, in pdfo
    prepdfo(fun, x0, args, method, bounds, constraints, options)
  File "C:\Users\dimo\AppData\Roaming\Python\Python312\site-packages\pdfo\_common.py", line 407, in prepdfo
    import_error_so('gethuge')
  File "C:\Users\dimo\AppData\Roaming\Python\Python312\site-packages\pdfo\_common.py", line 3501, in import_error_so
    raise ImportError('{} is missing. Please reinstall {} and ensure the '
ImportError: gethuge is missing. Please reinstall pdfo and ensure the fulfilment of the requirements (numpy>=1.20.0).
```

I use python version 3.12.3 under Windows 10. The version of pdfo (freshly installed via pip) is 2.1.0, numpy version is 2.2.0.

**Comment by brockho** [comment]
Hello,

Just to reiterate: the same happens under Linux as well. All requirements seem to be fulfilled (in particular for numpy) and also uninstalling and reinstalling pdfo does not help.
