### ISSUE TITLE
can fun_c be parallel for initial m evaluations?

### ISSUE THREAD

**Issue by roger-lee-0038** [pdfo/pdfo#58]
Hello~ thanks for your excellent work firstly! 
The question is when I tried to apply bobyqa to optimize an expensive black box function, I found it can be time-consuming during the initial m=2n+1 evaluations. I think modify the fun_c defined in prepdfo to support parallel evaluations will be helpful e. g. receive a m*n ndarray and return a m*1 ndarray. But it seems that I should also modify the function interface of the fortran code, which is challenge as I'm not familiar with fortran.
So do you have some advice or maybe have you ever dealt with the problem of parallel evaluations?
Sincerely

**Comment by ragonneau** [comment]
Dear @roger-lee-0038,

Sorry for the delay. I totally understand your request. It is however not possible for the moment to perform these evaluations in parallel. PDFO interfaces Powell's code without modifying it (we only patched some bugs). Moreover, doing parallel evaluations in Fortran would require using a framework such as OpenMP, which would complicate greatly the compilation of the package.

I come back to you in the future if any change is made in that direction.

Cheers,
Tom.

**Comment by roger-lee-0038** [comment]
get it, and thank you very much🙂发自我的手机-------- 原始邮件 --------发件人： "Tom M. Ragonneau" ***@***.***>日期： 2023年6月25日周日 下午3:09收件人： pdfo/pdfo ***@***.***>抄送： roger_lee ***@***.***>, Mention ***@***.***>主    题： Re: [pdfo/pdfo] can fun_c be parallel for initial m evaluations? (Issue #58)
Dear @roger-lee-0038,
Sorry for the delay. I totally understand your request. It is however not possible for the moment to perform these evaluations in parallel. PDFO interfaces Powell's code without modifying it (we only patched some bugs). Moreover, doing parallel evaluations in Fortran would require using a framework such as OpenMP, which would complicate greatly the compilation of the package.
I come back to you in the future if any change is made in that direction.
Cheers,
Tom.
