### ISSUE TITLE
The documentation should mention less about the individual functions that are deprecated

### ISSUE THREAD

**Issue by zaikunzhang** [pdfo/pdfo#61]
The page at https://pdfo.net/user/usage.html mentions too much about the individual functions `newuoa` etc. It should be modified. See https://github.com/libprima/prima/blob/main/README_mat.md#usage for a reference.

**Comment by ragonneau** [comment]
Hi @zaikunzhang,

No problem, I take care of this today.

Regards,
Tom.

**Comment by ragonneau** [comment]
It is solved with e17f3245221bf35b5db4a35c0f586b738d678765.

Feel free to reopen if I missed something.

Cheers,
Tom.
