### ISSUE TITLE
How to print intermediate information 

### ISSUE THREAD

**Issue by szppp** [pdfo/pdfo#70]
Hello! When I was using pdfo, I want to print intermediate information so that I can know how the optimization is going. What's more, apart from objective function value, intermediate x is also useful to know the trend. Thanks!

**Comment by ragonneau** [comment]
Hi @szppp,

Sorry for not getting back to you sooner. In the current state, we only print information at the end of the optimization process. You might print what you need inside your objective/constraint function. See for example the code below that minimizes the Rosenbrock function in Python.

```python
from pdfo import pdfo


def rosen(x):
    # Replace the evaluation below by the evaluation you are interested in.
    f = sum(100.0 * (x[1:] - x[:-1]**2.0)**2.0 + (1 - x[:-1])**2.0)

    # Print the evaluation.
    print(f'rosen({x}) = {f}')

    # Return the function evaluation.
    return f


if __name__ == '__main__':
    pdfo(rosen, [0, 0, 0], options={'quiet': False})
```

The same thing can be done in MATLAB (let me know if you need an example). We are currently working on two other packages for solving DFO problems which can print intermediate information for you:
1. [COBYQA](https://www.cobyqa.com): a new method for solving general optimization problems.
2. [PRIMA](https://github.com/libprima/prima): a modernization of Powell DFO methods.
They might be of interest for you.

Let me know if you need any further information,
Cheers,
Tom.

**Comment by szppp** [comment]
> Hi @szppp,
> 
> Sorry for not getting back to you sooner. In the current state, we only print information at the end of the optimization process. You might print what you need inside your objective/constraint function. See for example the code below that minimizes the Rosenbrock function in Python.
> 
> ```python
> from pdfo import pdfo
> 
> 
> def rosen(x):
>     # Replace the evaluation below by the evaluation you are interested in.
>     f = sum(100.0 * (x[1:] - x[:-1]**2.0)**2.0 + (1 - x[:-1])**2.0)
> 
>     # Print the evaluation.
>     print(f'rosen({x}) = {f}')
> 
>     # Return the function evaluation.
>     return f
> 
> 
> if __name__ == '__main__':
>     pdfo(rosen, [0, 0, 0], options={'quiet': False})
> ```
> 
> The same thing can be done in MATLAB (let me know if you need an example). We are currently working on two other packages for solving DFO problems which can print intermediate information for you:
> 
> 1. [COBYQA](https://www.cobyqa.com): a new method for solving general optimization problems.
> 2. [PRIMA](https://github.com/libprima/prima): a modernization of Powell DFO methods.
>    They might be of interest for you.
> 
> Let me know if you need any further information, Cheers, Tom.

Thanks for your detailed reply! I'll try them.
