### ISSUE TITLE
Is pdfo a local optimization algorithm?

### ISSUE THREAD

**Issue by longbiscuit** [pdfo/pdfo#83]
I tried to use the matlab version of pdfo to find the minimum of the following function, but it did not work well. Is pdfo a local optimization algorithm?

```matlab
clc
clear all;
close all;

problem = struct();
problem.objective = @ChenxianyunFunc;
problem.x0 = [10,10];
problem.lb = [0,0];
problem.ub = [50,50];
problem.options.maxfun = 500;
x = pdfo(problem)


function z = ChenxianyunFunc(x)
% 答案：
% 目标函数值(最小): -715.775061146149
% x1: 20.4786412351456
% x2: 25.066028561025
x1=x(1);
x2=x(2);
z = -40*x1*cos(x2)-35*x2*sin(x1)+15*x1^2-sin(x1)*20+12*x2^2-25*x1*x2*sin(x1*x2^2*cos(x1+x2));
end
````

![image](https://github.com/pdfo/pdfo/assets/21994802/680766b9-b4d7-4440-ba3d-3d38441432f5)

**Comment by zaikunzhang** [comment]
Hi, 

Thank you for your message. 

Yes, PDFO solvers are all local. If you intend to find the global minimum, you may try invoking PDFO with multiple randomly generated starting points. 

BTW, if you are using MATLAB, I suggest you  try PRIMA, http://www.libprima.net , which provides the same solvers but improved.

**Comment by zaikunzhang** [comment]
Hi @longbiscuit , I am closing this issue since the question is answered. Feel free to reopen it or open a new one if you like. Thanks.
